/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yutaka' at '15/12/06 23:07' with Gradle 2.9
 *
 * @author yutaka, @date 15/12/06 23:07
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
