import org.junit.Test;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'yutaka' at '15/12/06 22:25' with Gradle 2.9
 *
 * @author yutaka, @date 15/12/06 22:25
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
