/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Takumi' at '15/12/06 22:25' with Gradle 2.9
 *
 * @author Takumi, @date 15/12/06 22:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
